### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/OptimalControl.jl#251]
See https://github.com/control-toolbox/CTDirect.jl/issues/115#issuecomment-2252405792

**Comment by jbcaillau** [comment]
@ocots hadn't you written a global list of todo's for 1.0.0? can't find nothing more than scattered issues (which is fine, but would like some prioritisation)

**Comment by ocots** [comment]
@jbcaillau I can't find any list. Maybe we can do one.

**Comment by ocots** [comment]
Things we can do before the new release `v1.0.0`.

This some info [here](https://juliahub.com/ui/Packages/General/OptimalControl) about `OptimalControl.jl`.

**Reference.**

- [ ] https://github.com/control-toolbox/OptimalControl.jl/issues/175. https://github.com/control-toolbox/OptimalControl.jl/issues/166

**Documentation.**

- [ ] https://github.com/control-toolbox/OptimalControl.jl/issues/253. We should add a description of the algorithms. In `OptimalControl.jl` documentation, we should add a page about `Solvers` and briefly describe the `solve` function. In `CTDirect.jl` we should have a more detailed presentation of the discretization scheme with the ordering of the variables...
- [ ] https://github.com/control-toolbox/OptimalControl.jl/issues/194. https://github.com/control-toolbox/OptimalControl.jl/issues/155. We should add a tutorial about the abstract formulation.
- [ ] https://github.com/control-toolbox/OptimalControl.jl/issues/165. We could compare `MINPACK` and `NonlinearSolve` in the tutorial about `Indirect simple shooting`. We could add a test to avoid crash if using an `arm` system since `MINPACK` is not supported: see [here](https://github.com/IanButterworth/SystemBenchmark.jl/blob/004fb3cc045b6ede529d2e6290e338ece8c8fbb4/src/SystemBenchmark.jl#L28) or a simple `try ... catch`.

**Enhancement.**

- [ ] https://github.com/control-toolbox/CTBase.jl/issues/204
- [ ] https://github.com/control-toolbox/CTBase.jl/issues/201
- [ ] https://github.com/control-toolbox/CTFlows.jl/issues/30
- [ ] https://github.com/control-toolbox/CTDirect.jl/issues/115. We should fix the API.
- [ ] https://github.com/control-toolbox/CTFlows.jl/issues/19
- [ ] https://github.com/control-toolbox/OptimalControl.jl/issues/116

**Unit tests.**

- [ ] https://github.com/control-toolbox/CTDirect.jl/issues/184. Add tests.
- [ ] https://github.com/control-toolbox/CTBase.jl/issues/187
- [ ] https://github.com/control-toolbox/CTBase.jl/issues/182

**Bug.**

- [ ] https://github.com/control-toolbox/CTFlows.jl/issues/15

**Comment by jbcaillau** [comment]
manu thanks @ocots I've added 🚀 on the must-be-done-before-1.0.0 according to me. @PierreMartinon @gergaud feel free to update!

**Comment by ocots** [comment]
For me I have put a ⚽️

**Comment by ocots** [comment]
I have added `MINPACK` in the indirect simple shooting tutorial and the Goddard problem. I have to check that there is no error since I have added a `try...catch` to switch from `hybrj` to `hybrd` when an error occurs since with my computer I cannot use `hybrj` but `hybrd` is working.

**Comment by ocots** [comment]
We should also add a tutorial about how to improve performance installing `HSL`, using the best linear solver, etc.

**Comment by jbcaillau** [comment]
> I have added `MINPACK` in the indirect simple shooting tutorial and the Goddard problem. I have to check that there is no error since I have added a `try...catch` to switch from `hybrj` to `hybrd` when an error occurs since with my computer I cannot use `hybrj` but `hybrd` is working.

@ocots nice. if not already done, I guess we can remove the dependency towards NonlinearSolve 💩

**Comment by ocots** [comment]
No there will be both.

**Comment by jbcaillau** [comment]
> No there will be both.

where do we (still) need NonlinearSolvePoo?

**Comment by ocots** [comment]
> > No there will be both.
> 
> where do we (still) need NonlinearSolvePoo?

Tutorials:

- Indirect simple shooting
- Goddard

Maybe other.

**Comment by jbcaillau** [comment]
OK: thought you had gone back to MINPACK for these.

**Comment by ocots** [comment]
I think we should add:

- a tutorial about how to optimize the code, cf. https://github.com/0Yassine0/COTS.jl.
- a tutorial (in manual part) about the solvers, cf. https://github.com/control-toolbox/OptimalControl.jl/issues/253.
- a tutorial (in manual part) about the use of the `Flow` function.

Actually the two first points are indicated in the list above. I should add something about the `Flow` function.

**Comment by jbcaillau** [comment]
> I think we should add:
> 
> * a tutorial about how to optimize the code, cf. https://github.com/0Yassine0/COTS.jl.
what do you mean? user stuff like changing the linear solver (HSL...), using MKL...?

we are far from optimal right now, but that's a dev (not user) issue, including (but not limited to):
- building a better (AD)NLP model https://github.com/control-toolbox/CTDirect.jl/issues/183#issuecomment-2268306797
- using in place https://github.com/control-toolbox/CTDirect.jl/issues/188

> * a tutorial (in manual part) about the solvers, cf. [Document algorithms #253](https://github.com/control-toolbox/OptimalControl.jl/issues/253).
- the user cannot do much about ordering

> * a tutorial (in manual part) about the use of the `Flow` function.
- right!

> Actually the two first points are indicated in the list above. I should add something about the `Flow` function.

**Comment by jbcaillau** [comment]
To me only two things left before v1.0.0:
> * [ ] @PierreMartinon 🚀 [Adjoint (dynamics multipliers) parsing CTDirect.jl#184](https://github.com/control-
> * [ ] @ocots 🚀 [Flow with variables (NonFixed ocp) CTFlows.jl#15](https://github.com/control-toolbox/CTFlows.jl/issues/15)

Gents... 🙂

**Comment by ocots** [comment]
> > I think we should add:
> > 
> > * a tutorial about how to optimize the code, cf. https://github.com/0Yassine0/COTS.jl.
> >   what do you mean? user stuff like changing the linear solver (HSL...), using MKL...?

Yes, we could do something like: https://docs.sciml.ai/NonlinearSolve/stable/tutorials/code_optimization/

Just simple things like you said: changing the linear solver, using MKL. Saying that it is possible to change the AD backend without any comparison. It is maybe more tuning than optimising that we should say. But I think we can profit from what @0Yassine0 did to explain some possibilities. It shows the versatility of our package.

> 
> we are far from optimal right now, but that's a dev (not user) issue, including (but not limited to):
> 
> * building a better (AD)NLP model [Pass sparse structure of constraints to NLPModels CTDirect.jl#183 (comment)](https://github.com/control-toolbox/CTDirect.jl/issues/183#issuecomment-2268306797)
> * [Use inplace when building the NLP model CTDirect.jl#188](https://github.com/control-toolbox/CTDirect.jl/issues/188)

I was not thinking of this.

> > * a tutorial (in manual part) about the solvers, cf. [Document algorithms #253](https://github.com/control-toolbox/OptimalControl.jl/issues/253).
> 
> * the user cannot do much about ordering

I was simply thinking about the fact that the user can choose the method to solve its problem. For the moment, there is only one case: see

https://github.com/control-toolbox/OptimalControl.jl/blob/2ae8993dfb9c32abd16dba1fd376939b13b58f63/src/solve.jl#L9

But, later there will be more. I thought about a simple tutorial explaining how to choose the method with its description. We could profit to redirect to the documentation of the packages we use, like `ADNLPModels.jl`, `NLPModelsIpopt.jl` and `CTDirect.jl`.

> 
> > * a tutorial (in manual part) about the use of the `Flow` function.
> 
> * right!
> 
> > Actually the two first points are indicated in the list above. I should add something about the `Flow` function.

**Comment by ocots** [comment]
> Enhancement

I am going to continue on the `Enhancement` part and this bug to correct.

**Comment by jbcaillau** [comment]
> I was simply thinking about the fact that the user can choose the method to solve its problem. For the moment, there is only one case: see
> 
> https://github.com/control-toolbox/OptimalControl.jl/blob/2ae8993dfb9c32abd16dba1fd376939b13b58f63/src/solve.jl#L9
> 
> But, later there will be more. I thought about a simple tutorial explaining how to choose the method with its description. We could profit to redirect to the documentation of the packages we use, like `ADNLPModels.jl`, `NLPModelsIpopt.jl` and `CTDirect.jl`.

@ocots @PierreMartinon we should immediately add MadNLP: https://github.com/control-toolbox/OptimalControl.jl/issues/259 Works out of the box (check https://github.com/control-toolbox/OptimalControl.jl/pull/260) and @frapac can help in case of need 🙂

**Comment by PierreMartinon** [comment]
Regarding MadNLP, I have one question: I don't know how to have the CTSolveExt extension loaded if *either* `NLPModelsIpopt` or `MadNLP` are used. From the Julia doc, a package extension will load if *all* its dependencies are present...

**Comment by PierreMartinon** [comment]
For the sparsity pattern, the current trapeze method makes it a bit more involved: we typically store the dynamics at the end of a time step before moving on to the next step, so that we don't compute it twice. This complicates the decomposition of the constraints as a simple loop over the time steps, and the resulting sparsity pattern.

**Comment by ocots** [comment]
> Regarding MadNLP, I have one question: I don't know how to have the CTSolveExt extension loaded if _either_ `NLPModelsIpopt` or `MadNLP` are used. From the Julia doc, a package extension will load if _all_ its dependencies are present.
> 
> We could try to have one extension per solver, but this is not how we currently work: we have a single function with a Symbol argument for the solver, not several methods with multiple dispatch...

![Capture d’écran 2024-08-05 à 17 57 16](https://github.com/user-attachments/assets/fe30444c-4652-4b6e-901c-a1434e817d73)

La première fonction `solve` se trouve dans les sources tandis que celle sur les types concrets se trouvent dans 2 extensions séparées.

**Comment by jbcaillau** [comment]
> We could try to have one extension per solver [...]

@PierreMartinon that is what I would favor, again to avoid load time issues (= just load the relevant extension when triggered by the chosen solver).

**Comment by jbcaillau** [comment]
> For the sparsity pattern, the current trapeze method makes it a bit more involved: we typically store the dynamics at the end of a time step before moving on to the next step, so that we don't compute it twice. This complicates the decomposition of the constraints as a simple loop over the time steps, and the resulting sparsity pattern.

@PierreMartinon oh, right. spares half the computation. nice.

**Comment by ocots** [comment]
@PierreMartinon bien sûr le `solve` correspond à ton `solve_docp`.

**Comment by PierreMartinon** [comment]
First madnlp tests https://github.com/control-toolbox/CTDirect.jl/pull/191

**Comment by jbcaillau** [comment]
> To me only two things left to go 1.0.0:
> 
> > * [ ]  @PierreMartinon 🚀 [Adjoint (dynamics multipliers) parsing CTDirect.jl#184](https://github.com/control-
> > * [x]  @ocots 🚀 [Flow with variables (NonFixed ocp) CTFlows.jl#15](https://github.com/control-toolbox/CTFlows.jl/issues/15)
> 
> Gents... 🙂

@PierreMartinon one step away from 1.0.0 🤞🏽
> https://github.com/control-toolbox/CTDirect.jl/issues/184

**Comment by ocots** [comment]
> @PierreMartinon bien sûr le `solve` correspond à ton `solve_docp`.
> 
> Voui. La je coince sur ces ù*^$ de descriptions: je voudrais rajouter et tester le cas :madnlp au lieu de :ipopt, mais je ne trouve pas la bonne syntaxe -_- J'ai essaye de completer available_methods et de passer :madnlp au solve, mais pas moyen. C'est une liste de couples, ou bien une liste tout court ?
> 
> ```
> algorithms=()
> algorithms = add(algorithms, (:adnlp, :ipopt))
> algorithms = add(algorithms, (:adnlp, :madnlp))
> ```
> 
> ```
> available_methods()
> MethodError: Cannot `convert` an object of type 
>   Tuple{Tuple{Symbol,Symbol},Tuple{Symbol, Symbol}} to an object of type 
>   Tuple{Tuple{Vararg{Symbol}}}
> ```
> 
> Pas sur non plus de comprendre comment fonctionne getFullDescription avec ses priorites.
> 
> Finalement est-ce qu'on ne ferait pas mieux de revenir a de bons vieux kwargs avec des valeurs par defaut ?
> 
> Edit: bon j'ai juste enleve le type de available_methods() et ca semble marcher

Désolé le bon type était : `Tuple{Vararg{Tuple{Vararg{Symbol}}}}`.

**Comment by jbcaillau** [comment]
@ocots @PierreMartinon thanks for the active cleaning / upgrading (`solve` and everything) 👍🏽. was beach / boat day on may side 🌞

**Comment by PierreMartinon** [comment]
The parsing for the constraints multipliers should be up in the next release. Untested though.

Before 1.0 I'd like to 
- add a second discretization scheme (implicit midpoint). Adding other schemes later should be easier.
- then try to pass the sparsity structure and see what performance we get.

**Comment by jbcaillau** [comment]
> The parsing for the constraints multipliers should be up in the next release. Untested though.
> 
> Before 1.0 I'd like to
> 
> * add a second discretization scheme (implicit midpoint). Adding other schemes later should be easier.

Not a priority, I think. I am not expecting big changes from midpoint (dual to trapezoidal scheme with more or less the same properties). Having a higher order would be nice (see https://github.com/control-toolbox/CTDirect.jl/issues/101#issuecomment-2278117351) but not top priority for most i use case.

> * then try to pass the sparsity structure and see what performance we get.
more important, yes: see https://github.com/control-toolbox/CTDirect.jl/issues/183#issuecomment-2272012662 (ADNLPModels way, instead of a fully manual process through NLPModels - if I got correctly)

But even more important (see this other exchange with @amontoison, https://github.com/control-toolbox/CTDirect.jl/issues/188#issuecomment-2269933107)

**Comment by PierreMartinon** [comment]
I know, but I can't really pass the sparse structure with the trapeze method (more blocks than a true single step method due to each dynamics acting on two steps and not just one, and also the saving of this dynamics for the next step complicates things).

**Comment by jbcaillau** [comment]
@PierreMartinon ah ok. but I think you can. independently on how you (efficiently) you compute the constraint, its value is sth like
```math
x_{i+1} - x_i - (t_{i+1} - t_i) / 2 (f(x_i, u_i) + f(x_{i+1},u_{i+1})
```
for which the derivative *wrt.* $x_i$'s and $u_i$'. Agree?

**Comment by jbcaillau** [comment]
@PierreMartinon available for a quick call to decide on publishing 1.0?

**Comment by PierreMartinon** [comment]
> @PierreMartinon available for a quick call to decide on publishing 1.0?

Eh, more likely next week. Do we have a deadline for 1.0, conf or something ?

**Comment by jbcaillau** [comment]
> > @PierreMartinon available for a quick call to decide on publishing 1.0?
> 
> Eh, more likely next week. Do we have a deadline for 1.0, conf or something ?

@PierreMartinon no deadline, just not bad to proceed according to what was planned above. next Monday? 15:00?

**Comment by PierreMartinon** [comment]
> > > @PierreMartinon available for a quick call to decide on publishing 1.0?
> > 
> > 
> > Eh, more likely next week. Do we have a deadline for 1.0, conf or something ?
> 
> @PierreMartinon no deadline, just not bad to proceed according to what was planned above. next Monday? 15:00?

@jbcaillau Bump

**Comment by jbcaillau** [comment]
@PierreMartinon meeting scheduled tonight 21:00
https://univ-cotedazur.zoom.us/my/caillau

To discuss: 
- https://github.com/control-toolbox/OptimalControl.jl/issues/251
- https://github.com/control-toolbox/CTBase.jl/issues/232
- https://github.com/control-toolbox/CTDirect.jl/discussions/111#discussioncomment-10376352

**Comment by jbcaillau** [comment]
> @PierreMartinon meeting scheduled tonight 21:00 https://univ-cotedazur.zoom.us/my/caillau
> 
> To discuss:
> 
> * [Release 1.0.0 #251](https://github.com/control-toolbox/OptimalControl.jl/issues/251)
> * [Preparing for inplace NLP CTBase.jl#232](https://github.com/control-toolbox/CTBase.jl/issues/232)
> * [ADNLPModel new shiny stuff CTDirect.jl#111 (reply in thread)](https://github.com/control-toolbox/CTDirect.jl/discussions/111#discussioncomment-10376352)

@ocots @gergaud please join if you're around 🤞🏾

**Comment by PierreMartinon** [comment]
Breakage seems to work: https://github.com/control-toolbox/CTDirect.jl/pull/209#issuecomment-2298473309

**Comment by PierreMartinon** [comment]
Constraints / multipliers parsing *seems* to work: https://github.com/control-toolbox/CTDirect.jl/pull/210

**Comment by jbcaillau** [comment]
@ocots @PierreMartinon hi. CTModels.jl and CTParser.jl will need to be added to the general registry. what is the good process / schedule to do so and seamlessly update OptimalControl.jl?

**Comment by ocots** [comment]
Try to make a program before `v1.0.0`.

## CTModels.jl

- The package needs to be completed: plot of a solution, print of an ocp... See the [issues](https://github.com/control-toolbox/CTModels.jl/issues).
- Then, we can go to the general registry. Simply follow these [steps](https://github.com/control-toolbox/control-toolbox.github.io/wiki/Make-a-release#register-in-the-general-registry-and-tag).

## CTParser.jl

- It has to be updated to follow the new functions of CTModels.jl.
- First, it has to point to the `main` branch of CTModels.jl. Once CTModels.jl is in the general registry, then, it must point to the package as usual.
- Then, it can be added to the general registry.

**Remark.** About the qualification (or prefixing), maybe we can have in CTParser.jl, a `@def` macro that takes a module name as a **required** keyword. Then, in OptimalControl.jl, it would be sufficient to overload the `@def` macro fixing the keyword.

## CTDirect.jl 

- Once CTModels.jl is in the general registry, then, it must point to the package as usual.
- Then, a new release must be done.

## CTFlows.jl

As CTParser.jl.

## OptimalControl.jl

- When CTModels.jl and CTParser.jl are in the general registry, and when CTDirect.jl and CTFlows.jl have a new release, we can update OptimalControl.jl and make a new release.

## CTBase.jl

When all written before is done, then, we must clean CTBase.jl, removing unnecessary code. We can check there is no problem before making a new release by creating branches in the other packages that point to the cleaned branch of CTBase.jl.

**Comment by ocots** [comment]
I will clean CTBase.jl. Actually, it is already done in this [branch](https://github.com/control-toolbox/CTBase.jl/tree/cleaning).

**Comment by jbcaillau** [comment]
> I will clean CTBase.jl. Actually, it is already done in this [branch](https://github.com/control-toolbox/CTBase.jl/tree/cleaning).

@ocots nice. have you tried to run CTModels (that uses / imports CTBase) with this particular branch? BTW, what is the best way to do so?

**Comment by jbcaillau** [comment]
@ocots EDIT after our discussion 🙏🏽: 
- have specific defaults.jl + exceptions.jl + utils.jl in every package
- also add such files in CTBase.jl when there is sth to factorise to avoid code duplication (*e.g.*, descriptions, label generation with sub/sup-scripts...)
- make a release of CTBase from the `cleaning` branch asap and use it with CTModels + CTParser (`compat` will prevent any issue with existing packages)
- for yet unregistered packages (CTModels + CTParser) use `where` (rather than dev or a local registry)

**Comment by ocots** [comment]
Our discussion 

![IMG-20250219-WA0004.jpg](https://github.com/user-attachments/assets/30254801-41d8-4e0b-9931-dc3b54fc6680)

**Comment by jbcaillau** [comment]
I can see goku but where are the huskies?

**Comment by PierreMartinon** [comment]
Hi there. Before jumping to 1.0.0 I'd like to make a new release of OptimalControl since it uses a really old version of CTDirect. I have a compatibility problem with CTBase: CTDirect requires 0.14 but CTFlows does not seem to work with it. If it's related to the inplace aspect, we could add the option to the def macro and use in_place=false with CTFlows ?

**Comment by jbcaillau** [comment]
sure. but i don't remember the original of the problem.

**Comment by ocots** [comment]
> Hi there @jbcaillau @ocots . Before jumping to 1.0.0 I'd like to make a new release of OptimalControl since it uses a really old version of CTDirect. I have a compatibility problem with CTBase: CTDirect requires 0.14 but CTFlows does not seem to work with it. If it's related to the inplace aspect, we could add the option to the def macro and use in_place=false with CTFlows ? 

I will take a look today.

**Comment by PierreMartinon** [comment]
Ok, you tell me. Worst case scenario, I'll only update CTDirect to 0.13.1 and leave the rest as is. My updates on the docs for OptimalControl can stay on the https://github.com/control-toolbox/OptimalControl.jl/tree/ctdirect-0.13 branch for now.

**Comment by jbcaillau** [comment]
@ocots a bit painful to dev CTParser without having
- a registered release of CTModels (github CI prefers registered dependencies)
- a new release of CTBase (based on `cleaning` branch)

**Comment by ocots** [comment]
> [@ocots](https://github.com/ocots) a bit painful to dev CTParser without having
> 
> * a registered release of CTModels (github CI prefers registered dependencies)
> * a new release of CTBase (based on `cleaning` branch)
> 
> using Pkg # debug: also remove Pkg from test/Project.toml
> Pkg.add(url="https://github.com/control-toolbox/CTModels.jl") # debug
> import CTModels # debug: should eventually be OptimalControl (that will reexport CTModels func. primitives)
> 
> #
> @testset verbose = true showtiming = true "CTParser tests" begin
> [...]
> end
> 
> Pkg.rm("CTModels") # debug

I am wondering if the parser should not be in OptimalControl.jl. Is not OptimalControl.jl the parser?

**Comment by ocots** [comment]
- I make the new releases for @PierreMartinon.
- I create a new release of CTBase.jl for @jbcaillau. I add CTModels.jl now in the general registry. I will complete it later.

**Comment by ocots** [comment]
We must change CTModels name:

>Package name similar to 3 existing packages.
>Similar to Models. Damerau-Levenshtein distance 2 is at or below cutoff of 2.
>Similar to EHTModels. Damerau-Levenshtein distance 2 is at or below cutoff of 2.
>Similar to ACTRModels. Damerau-Levenshtein distance 2 is at or below cutoff of 2.

**Comment by PierreMartinon** [comment]
@ocots, Thanks, I'll check the new CTFlows for OptimalControl !

Regarding the CTModels/CTBase[cleaning], from CTDirect we need:
- initial guess part (do we move it all from CTBase to CTModels ?)
- less important, some intermediate solution constructors where we would pass the primal and dual variables separately

**Comment by PierreMartinon** [comment]
> We must change CTModels name:
> 
> > Package name similar to 3 existing packages.
> > Similar to Models. Damerau-Levenshtein distance 2 is at or below cutoff of 2.
> > Similar to EHTModels. Damerau-Levenshtein distance 2 is at or below cutoff of 2.
> > Similar to ACTRModels. Damerau-Levenshtein distance 2 is at or below cutoff of 2.

CTModelsOCP ?

**Comment by jbcaillau** [comment]
@PierreMartinon @ocots would prefer to try and enforce CTModels.jl (no issue with the CT prefix)

> > We must change CTModels name:
> > > Package name similar to 3 existing packages.
> > > Similar to Models. Damerau-Levenshtein distance 2 is at or below cutoff of 2.
> > > Similar to EHTModels. Damerau-Levenshtein distance 2 is at or below cutoff of 2.
> > > Similar to ACTRModels. Damerau-Levenshtein distance 2 is at or below cutoff of 2.
> 
> CTModelsOCP ?

**Comment by jbcaillau** [comment]
@PierreMartinon for mayer and lagrange functions, do you want `inplace`?

**Comment by PierreMartinon** [comment]
@ocots  If I just rename `direct_solve` as `solve`, won't there be conflicts with OptimalControl ? I currently export `direct_solve`.

**Comment by PierreMartinon** [comment]
Ok, I'll do the update on https://github.com/control-toolbox/OptimalControl.jl/tree/251-release-100

**Comment by jbcaillau** [comment]
@PierreMartinon https://github.com/control-toolbox/CTParser.jl/pull/16#issuecomment-2740016137

**Comment by jbcaillau** [comment]
> However, if I remove the `set_prefix` call, I keep getting an undefined error for PreModel, even when adding an explicit import. How do you get it to work with only using OptimalControl ?
> 
> Are we missing a (re)export somewhere ? Currently neither CTModels or OptimalControl export PreModel.

@PierreMartinon exactly, yes. on it 🤞🏽

**Comment by jbcaillau** [comment]
@ocots second thoughts:
- as a dev, it is nice to import instead of using in order to avoid name conflicts (and redefine things, *etc.*)
- but, in OptimalControl.jl (top repo), in order to avoid such boilerplate as `foo = X.foo` (then export), for (re)exported routines I think it is better to (i) export foo in X, (ii) `using X` in OptimalControl.jl and `export foo`

**Comment by jbcaillau** [comment]
@PierreMartinon Goddard indirect test, same params (that should be `const`, BTW) at three different places!?

```julia
function Goddard()

    # parameters
    Cd = 310
    Tmax = 3.5
    β = 500
    b = 2
    t0 = 0
    r0 = 1
    v0 = 0
    vmax = 0.1
    m0 = 1
    mf = 0.6
    x0 = [r0, v0, m0]

    # the model    
    @def ocp begin
        # parameters
        Cd = 310
        Tmax = 3.5
        β = 500
        b = 2
        t0 = 0
        r0 = 1
        v0 = 0
        vmax = 0.1
        m0 = 1
        mf = 0.6
        x0 = [r0, v0, m0]
...
```

**Comment by jbcaillau** [comment]
@ocots please have a look at CTFlows imports / exports in there (might be some missing things):

https://github.com/control-toolbox/OptimalControl.jl/blob/cee6f39a4a6ecae51bdb0f2ad348ac014d1808a2/src/OptimalControl.jl#L40

**Comment by PierreMartinon** [comment]
> [@PierreMartinon](https://github.com/PierreMartinon) Goddard indirect test, same params (that should be `const`, BTW) at three different places!?
> 
> function Goddard()
> 
>     # parameters
>     Cd = 310
>     Tmax = 3.5
>     β = 500
>     b = 2
>     t0 = 0
>     r0 = 1
>     v0 = 0
>     vmax = 0.1
>     m0 = 1
>     mf = 0.6
>     x0 = [r0, v0, m0]
> 
>     # the model    
>     @def ocp begin
>         # parameters
>         Cd = 310
>         Tmax = 3.5
>         β = 500
>         b = 2
>         t0 = 0
>         r0 = 1
>         v0 = 0
>         vmax = 0.1
>         m0 = 1
>         mf = 0.6
>         x0 = [r0, v0, m0]
> ...
> 
> NB. no more `remove_constraint!`

I'm not the one in charge of the indirect tests :D But yes, it looks like the variables are duplicated, you can probably remove the ones inside the macro. You have the goddard problem definition for the direct tests in https://github.com/control-toolbox/OptimalControl.jl/blob/main/test/ctdirect/problems/goddard.jl

**Comment by jbcaillau** [comment]
@ocots @PierreMartinon @gergaud 

@ocots api-ctbase/
api-ctbase.md
api-ctdirect.md
api-ctflows.md
api-optimalcontrol.md
dev-ctbase.md
dev-ctdirect.md
dev-ctflows.md
dev-optimalcontrol.md

@ocots tutorial-flow.md
@ocots tutorial-iss.md
@ocots tutorial-plot.md

@jbcaillau juliacon2024.md
@jbcaillau oc_mam.md
@jbcaillau tutorial-abstract.md
@jbcaillau tutorial-goddard.md
@jbcaillau tutorial-double-integrator-energy.md
@jbcaillau tutorial-double-integrator-time.md
@jbcaillau tutorial-lqr-basic.md

@PierreMartinon tutorial-continuation.md
@PierreMartinon tutorial-discretisation.md
@PierreMartinon tutorial-nlp.md
@PierreMartinon tutorial-solve.md
@PierreMartinon tutorial-initial-guess.md

- créer une sous-branche, déplacer .md dans un rep local puis remettre avant PR

**Comment by ocots** [comment]
@joseph-gergaud The link to the double integrator example is not good. In the `index.md` file we have this:

https://github.com/control-toolbox/OptimalControl.jl/blob/52382c81e9fc7cf1766ec331ca4389d6ffc4c891/docs/src/index.md?plain=1#L71

But in the the `tutorial-double-integrator-energy.md` file we have:

https://github.com/control-toolbox/OptimalControl.jl/blob/52382c81e9fc7cf1766ec331ca4389d6ffc4c891/docs/src/tutorial-double-integrator-energy.md?plain=1#L1

Hence, `(@ref tutorial-double-integrator-energy)` must be replaced by `(@ref tutorial-basic)`, or `(@id tutorial-basic)` must be replaced by `(@id tutorial-double-integrator-energy)`.

**Comment by jbcaillau** [comment]
@ocots any news of the AD pb with CTFlows / NonlinearSolve?

**Comment by jbcaillau** [comment]
- [ ] @jbcaillau pb with `⋅` export (check in `test_goddard` to replace `Lie(...)` calls

**Comment by PierreMartinon** [comment]
> [@ocots](https://github.com/ocots) [@PierreMartinon](https://github.com/PierreMartinon) indirect test passed with MINPACK instead of NonlinearSolve (which is _de toute façon_ three times slower and with three times more alloys on Goddard 😅 than MINPACK.fsolve)

Ok, so we'll just remove the NonLinearSolve test ?

**Comment by PierreMartinon** [comment]
> * [ ]  [@jbcaillau](https://github.com/jbcaillau) pb with `⋅` export (check in `test_goddard` to replace `Lie(...)` calls

[Julia docs](https://docs.julialang.org/en/v1/manual/modules/#Qualified-names) says
`Due to syntactic ambiguities, qualifying a name that contains only symbols, such as an operator, requires inserting a colon, e.g. Base.:+`

Maybe we can try this ?

**Comment by jbcaillau** [comment]
> > [@ocots](https://github.com/ocots) [@PierreMartinon](https://github.com/PierreMartinon) indirect test passed with MINPACK instead of NonlinearSolve (which is _de toute façon_ three times slower and with three times more alloys on Goddard 😅 than MINPACK.fsolve)
> 
> Ok, so we'll just remove the NonLinearSolve test ?

I’ve *replaced* it by a MINPACK test (better an all point of view)

**Comment by ocots** [comment]
CR Réunion avec @PierreMartinon 04/04/2025

- @PierreMartinon va reprendre quelques documents de la doc que devait revoir @ocots et @jbcaillau, cf. https://github.com/control-toolbox/OptimalControl.jl/issues/251#issuecomment-2743807115.
- Pour la documentation, on propose : 
    - Remplacer "Introduction" par "Getting Started".
    - De supprimer dans l'introduction la partie mathematical problem qui n'apporte rien.
    -  Ajouter plus tard une explication algorthimique pour expliquer la démarche de notre boite à outils. La partie math serait ici et assez loin dans le menu de gauche de la doc.
    - Supprimer la partie "Basic examples". 
    - Ajouter dans les manuels, un manuel sur "Free time" où l'on met des exemples de problèmes avec temps final libre, min $t_f$ mais pas que, temps initial libre aussi. 
    - Dans les manuels, ajouter des liens vers les tutoriels pour voir une utilisation concrète sur un exemple et montrer où cela peut servir.

**Comment by jbcaillau** [comment]
salut les gars, tout bon pour moi. 

@PierreMartinon si jamais y a pas que moi qui ai des docs à finir ￼, tu peux commencer par celles de @ocots

**Comment by PierreMartinon** [comment]
Fait (branche olivier):
- mise a jour des graphes dans les pages dev-*.md
- mise a jour des sections dans tutorial-solve.md
- verification tutorial-plot.md (sauf le lien lqr cf page vide mais ca devrait etre bon une fois le fichier remis)

A faire (branche JB):
- goddard et les deux double integrator

**Comment by PierreMartinon** [comment]
> > > [@ocots](https://github.com/ocots) [@PierreMartinon](https://github.com/PierreMartinon) indirect test passed with MINPACK instead of NonlinearSolve (which is _de toute façon_ three times slower and with three times more alloys on Goddard 😅 than MINPACK.fsolve)
> > 
> > 
> > Ok, so we'll just remove the NonLinearSolve test ?
> 
> I’ve _replaced_ it by a MINPACK test (better an all point of view)

Hi @jbcaillau , are you going to do the same in tutorial-goddard ? The NonlinearSolve case seems to work there.

**Comment by ocots** [comment]
But in the tutorial for Goddard problem there are both NonlinearSolve and MINPACK: see [here](https://control-toolbox.org/OptimalControl.jl/stable/tutorial-goddard.html#Indirect-shooting). I suggest to keep both since for me MINPACK does not work. I have no problem with NonlinearSolve.

**Comment by ocots** [comment]
I try to make the documentation but after 30 minutes, still 

<img width="670" alt="Image" src="https://github.com/user-attachments/assets/3df97a0f-7439-4c8d-8739-7a65f08b53e5" />

**Comment by jbcaillau** [comment]
thanks @ocots @PierreMartinon everything seems to be ready to merge into main and release. only one question regarding newer version of CTBase and CTModels, please check https://github.com/control-toolbox/OptimalControl.jl/pull/431#issuecomment-2810712265

**Comment by ocots** [comment]
> thanks [@ocots](https://github.com/ocots) [@PierreMartinon](https://github.com/PierreMartinon) everything seems to be ready to merge into main and release. only one question regarding newer version of CTBase and CTModels, please check [#431 (comment)](https://github.com/control-toolbox/OptimalControl.jl/pull/431#issuecomment-2810712265)
> 
> NB:
> 
> * the doc errors when i try to build locally (still errors with NonLinearSolve and more) while it builds on the CI...
> * is it possible to retrieve the doc built by the CI (_e.g._ for a PR) or is it just lost? (when building on the CI on main, i know it is available in the gh-pages branch)

I do not see how you can retrieve the doc generated by the CI. Maybe you can do an `scp` at the end to put it where you want.
